Code-cleanup, bugfixes
lbryio/lbry-android pull request #1118
Opened 2021-01-12 15:16 UTC by pakar

## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Refactoring (no functional changes)
- [x] Other - Please describe: Cleanup of code

## Other information
While reviewing and trying to get a grip of the code-base i have made a few minor fixes and done some cleanup.

Do look a bit closer at the changes before merging.

2021-01-12 17:10 UTC, kekkyojin reviewed
FDroid build server seems to not be able to use Gradle 6.5. Currently, I am building LBRY Fdroid with 6.1.1 since the beginning.

The FDroid release could still use 6.1.1. Just commenting that it could be good to be able to use the same one, if it is going to be changed here.

2021-01-12 19:06 UTC, pakar commented
@kekkyojin Good catch.. Changed to 6.1.1.

2021-01-12 19:35 UTC, kekkyojin commented
Thanks, @pakar. I am right now testing to build it with 6.5 using the virtual machine which replicates the build server from FDroid, and it is working. When the virtual machine is created, the script is even adding 6.7. But, as I said, 6.1.1 works while also enabling new features on Android Studio.

If @akinwale is ok, the buildToolsVersion could also be updated. Currently, 29.0.1 is used, while FDroid cannot use it, so I have to 'sed' to change it into 29.0.2. It could be changed into a newer one, like 30.x.x. If it works on 'lbry-android' but there are problems on 'lbry-fdroid' I could again replace it with a version which works on their build server.

2021-01-13 15:09 UTC, kekkyojin commented
Thanks, @pakar1. When this is merged, I will remove the prebuild step on the FDroid build script.

2021-01-13 15:38 UTC, pakar commented
@kekkyojin @akinwale I'm done for now with this round of cleanup.

2021-01-18 19:36 UTC, akinwale requested changes
Hey, thank you for the code cleanup. Everything looks good except for the issues I raised regarding the automated build system.

2021-01-18 19:36 UTC, akinwale commented on app/build.gradle
> +        targetSdkVersion 30
These need to be left as they are. `targetSdkVersion` should only be changed if absolutely necessary (required by Google Play). `minSdkVersion` indicates the minimum supported Android version (which is 5.0, and we don't intend to stop supporting that yet).

2021-01-18 19:36 UTC, akinwale commented on app/build.gradle
> +    buildToolsVersion "29.0.2"
These values can be left as they are. We only have to change them if absolutely necessary as they would require modifications to the Docker image used for the automated CI builds.

2021-01-18 19:36 UTC, akinwale commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
The app does not require this permission.

2021-01-18 19:36 UTC, akinwale commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
Please revert the Gradle version back to 5.6.4. Again, we don't need to change anything that affects the automated builds unless absolutely necessary.

2021-02-16 16:03 UTC, akinwale commented
@pakar @pakar1 Will you be able to make the requested changes so that we can merge your changes?

2021-02-16 16:15 UTC, pakar commented
@akinwale I have not yet had the time to do any changes for those things.

The reason for updating the sdk versions is due to the current code is using features not available in previous sdk versions. Before i would switch back the the original (target/compile etc) versions i would need to add checks in the code to prevent failing on older phones. (see commit comments for those updates)

ACCESS_NETWORK_STATE is used by ExoPlayer.

For the gradle-bump this was mainly kept so the FDroid build uses the same version. See comment from @kekkyojin . This one i don't mind reverting.

2021-02-16 16:29 UTC, kekkyojin commented
ACCESS_NETWORK_STATE is used but not required. I agree it should be removed from this PR.

2021-03-08 19:16 UTC, akinwale commented
https://github.com/lbryio/lbry-android/pull/1164

2021-03-08 19:16 UTC, closed without merging